// ============================================
// Communication Agent (房东通讯Agent)
// Generates and formats rental applications for landlords
// ============================================

import { UserProfile, PassportInfo, ScoredProperty, ApplicationForm, RentalApplication } from './types';
import { formatPassportSummary } from './document-agent';

// Generate a complete rental application
export function generateApplication(
  userProfile: UserProfile,
  passportInfo: PassportInfo,
  selectedProperty: ScoredProperty,
  additionalNotes: string = ''
): RentalApplication {
  return {
    userProfile,
    passportInfo,
    selectedProperty,
    additionalNotes,
    submittedAt: new Date()
  };
}

// Format application as a display-friendly object
export function formatApplicationForDisplay(application: RentalApplication): ApplicationForm {
  return {
    personalInfo: {
      fullName: application.passportInfo.fullName,
      passportNumber: application.passportInfo.passportNumber,
      nationality: application.passportInfo.nationality,
      dateOfBirth: application.passportInfo.dateOfBirth,
      contactEmail: application.userProfile.contact || 'Not provided'
    },
    rentalDetails: {
      selectedProperty: `${application.selectedProperty.address}, ${application.selectedProperty.suburb}`,
      propertyAddress: application.selectedProperty.address,
      weeklyRent: application.selectedProperty.price,
      preferredMoveInDate: application.userProfile.moveInDate || 'Flexible'
    },
    scores: {
      matchScore: application.selectedProperty.matchScore,
      mapScore: application.selectedProperty.mapScore,
      totalScore: application.selectedProperty.totalScore
    }
  };
}

// Generate formatted message for landlord
export function generateLandlordMessage(application: ApplicationForm): string {
  const date = new Date().toLocaleDateString('en-AU', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  });

  return `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 RENTAL APPLICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📅 Submitted: ${date}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
👤 TENANT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Full Name: ${application.personalInfo.fullName}
Passport Number: ${application.personalInfo.passportNumber}
Nationality: ${application.personalInfo.nationality}
Date of Birth: ${application.personalInfo.dateOfBirth}
Contact Email: ${application.personalInfo.contactEmail}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏠 PROPERTY DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Property: ${application.rentalDetails.selectedProperty}
Weekly Rent: $${application.rentalDetails.weeklyRent}
Preferred Move-in: ${application.rentalDetails.preferredMoveInDate}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 APPLICATION SCORES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Match Score: ${application.scores.matchScore}%
Map Score: ${application.scores.mapScore}%
Total Score: ${application.scores.totalScore}%

These scores indicate:
• ${application.scores.matchScore >= 80 ? '✅ Excellent match for your requirements' : 
  application.scores.matchScore >= 60 ? '👍 Good match for your requirements' : 
  '⚠️ Partial match for your requirements'}
• ${application.scores.mapScore >= 80 ? '✅ Great location with excellent amenities' :
  application.scores.mapScore >= 60 ? '👍 Good location with decent amenities' :
  '⚠️ Location may have limited amenities nearby'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💼 RENTAL REQUIREMENTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Budget: $${application.rentalDetails.weeklyRent}/week
Preferred Areas: ${application.rentalDetails.selectedProperty.split(',')[1]?.trim() || 'As per property'}
Bedrooms: ${application.selectedProperty?.bedrooms || 'N/A'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📝 ADDITIONAL NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This application was generated through HomeMatch AI,
an intelligent rental matching system.

The applicant has provided their passport for verification
and all information has been collected through our
secure conversation system.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by HomeMatch AI | ${date}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
}

// Note: We need to add bedrooms to ApplicationForm
declare module './types' {
  interface ApplicationForm {
    selectedProperty?: {
      bedrooms?: number;
    };
  }
}

// Generate a simplified summary for display
export function generateApplicationSummary(application: ApplicationForm): {
  label: string;
  value: string;
  icon: string;
}[] {
  return [
    { label: 'Name', value: application.personalInfo.fullName, icon: '👤' },
    { label: 'Passport', value: application.personalInfo.passportNumber, icon: '🔢' },
    { label: 'Nationality', value: application.personalInfo.nationality, icon: '🌍' },
    { label: 'Email', value: application.personalInfo.contactEmail, icon: '📧' },
    { label: 'Property', value: application.rentalDetails.propertyAddress, icon: '🏠' },
    { label: 'Weekly Rent', value: `$${application.rentalDetails.weeklyRent}`, icon: '💰' },
    { label: 'Move-in', value: application.rentalDetails.preferredMoveInDate, icon: '📅' },
    { label: 'Match Score', value: `${application.scores.matchScore}%`, icon: '🎯' },
    { label: 'Map Score', value: `${application.scores.mapScore}%`, icon: '🗺️' },
    { label: 'Total Score', value: `${application.scores.totalScore}%`, icon: '⭐' },
  ];
}

// Copy to clipboard friendly format
export function generatePlainTextApplication(application: ApplicationForm): string {
  return `
RENTAL APPLICATION - HomeMatch AI
==================================

TENANT INFORMATION
------------------
Name: ${application.personalInfo.fullName}
Passport Number: ${application.personalInfo.passportNumber}
Nationality: ${application.personalInfo.nationality}
Date of Birth: ${application.personalInfo.dateOfBirth}
Contact Email: ${application.personalInfo.contactEmail}

PROPERTY DETAILS
-----------------
Property Address: ${application.rentalDetails.propertyAddress}
Weekly Rent: $${application.rentalDetails.weeklyRent}
Preferred Move-in Date: ${application.rentalDetails.preferredMoveInDate}

SCORES
------
Match Score: ${application.scores.matchScore}%
Map Score: ${application.scores.mapScore}%
Total Score: ${application.scores.totalScore}%

Application submitted: ${new Date().toLocaleString()}
  `.trim();
}

// Generate WhatsApp/Email friendly message
export function generateContactMessage(application: ApplicationForm): string {
  return encodeURIComponent(`
Hi, I'm interested in your property at ${application.rentalDetails.propertyAddress}.

My details:
- Name: ${application.personalInfo.fullName}
- Contact: ${application.personalInfo.contactEmail}
- Budget: $${application.rentalDetails.weeklyRent}/week
- Move-in: ${application.rentalDetails.preferredMoveInDate}

I found this property through HomeMatch AI and it matches my requirements with a ${application.scores.totalScore}% compatibility score.

Please let me know if the property is still available!
  `.trim());
}
